#!/bin/sh
# pre-condition:
#   git clone git://github.com/sunaot/dotfiles.git
#   vim >= version 7.0
cd ~
mv dotfiles .dotfiles

# backup
mkdir .rc_backup
mv .bashrc .rc_backup
mv .bash_profile .rc_backup
test -e .vimrc && mv .vimrc .rc_backup
test -e .vim   && mv .vim .rc_backup
test -e .screenrc && mv .screenrc .rc_backup
test -e .screen   && mv .screen .rc_backup
test -e .gitconfig       && mv .gitconfig .rc_backup
test -e .gitconfig-local && mv .gitconfig-local .rc_backup

# install
echo 'source .dotfiles/.bashrc' > .bashrc
echo 'source .dotfiles/.bash_profile' > .bash_profile
ln -s .dotfiles/.bash.d
ln -s .dotfiles/.bin
ln -s .dotfiles/.vimrc
ln -s .dotfiles/.vim
ln -s .dotfiles/.screenrc
ln -s .dotfiles/.screen
ln -s .dotfiles/.gitconfig
touch .gitconfig-local

# setup vim 
mkdir .vim/bundle
cd .vim/bundle
git clone git@github.com:gmarik/vundle.git vundle
cd ~

echo "to complete the vim installation, run vim and :BundleInstall"
echo "to complete the git installation, git config --global user.name 'your name'"
echo "to complete the git installation, git config --global user.email 'your@email.address'"

exit 0
