#!/bin/sh
# pre-condition:
#   git clone git://github.com/sunaot/dotfiles.git
#   vim >= version 7.0
cd ~
mv dotfiles .dotfiles

# backup
mkdir .rc_backup
mv .bashrc .rc_backup
mv .bash_profile .rc_backup
test -e .vimrc && mv .vimrc .rc_backup
test -e .vim   && mv .vim .rc_backup
test -e .screenrc && mv .screenrc .rc_backup
test -e .screen   && mv .screen .rc_backup

# install
ln -s .dotfiles/.bashrc
ln -s .dotfiles/.bash_profile
ln -s .dotfiles/.bash.d
ln -s .dotfiles/.bin
ln -s .dotfiles/.vimrc
ln -s .dotfiles/.vim
ln -s .dotfiles/.screenrc
ln -s .dotfiles/.screen

# setup vim 
mkdir .vim/bundle
cd .vim/bundle
git clone git://github.com/gmarik/vundle.git vundle
cd ~

echo "to complete the vim installation, run vim and :BundleInstall"
echo ""
echo "if you get git ssl access error, try"
echo ".gitconfig"
echo "[http]"
echo "    sslVerify = false"
echo ""

exit 0
